"""empty message

Revision ID: daf2b462a2a4
Revises: 
Create Date: 2020-12-22 17:46:49.687375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf2b462a2a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('adminName', sa.String(length=128), nullable=True),
    sa.Column('adminUserName', sa.String(length=128), nullable=True),
    sa.Column('adminTrueName', sa.String(length=128), nullable=True),
    sa.Column('adminPhone', sa.String(length=11), nullable=True),
    sa.Column('adminEmail', sa.String(length=32), nullable=True),
    sa.Column('adminCreateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_adminCreateTime'), 'admin', ['adminCreateTime'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('userName', sa.String(length=128), nullable=True),
    sa.Column('userPhone', sa.String(length=11), nullable=True),
    sa.Column('userTrueName', sa.String(length=128), nullable=True),
    sa.Column('userPassword', sa.String(length=128), nullable=True),
    sa.Column('userCreateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_userCreateTime'), 'user', ['userCreateTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userCreateTime'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_admin_adminCreateTime'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
